/* 1oltmot.as
 * author: Aphelion
 */

// -- MISC

const uint WORKSHOP_CHAINSAW_WOOD_COST = 50;
const uint WORKSHOP_CHAINSAW_STONE_COST = 100;
 
// -- MARKET
const uint TRADER_FOOD_BREAD_COST = 5;
const uint TRADER_FOOD_COOKED_FISH_COST = 5;
const uint TRADER_FOOD_BURGER_COST = 10;
const uint TRADER_FOOD_CAKE_COST = 20;

// -- BLACKSMITH

const uint TRADER_PLATE_IRON_COST = 20;      // 45
const uint TRADER_PLATE_STEEL_COST = 40;     // 85
const uint TRADER_PLATE_MYTHRIL_COST = 85;   // 130
const uint TRADER_PLATE_ADAMANT_COST = 150;  // 225
const uint TRADER_PLATE_GOLD_COST = 320;
const uint TRADER_SWORD_IRON_COST = 12;      // 20
const uint TRADER_SWORD_STEEL_COST = 25;     // 45
const uint TRADER_SWORD_GOLD_COST = 160;
const uint TRADER_UNIQUE_MACE_COST = 55;     // 63
const uint TRADER_UNIQUE_WAR_AXE_COST = 105; // 120
const uint TRADER_CHAIN_IRON_COST = 12;
const uint TRADER_CHAIN_STEEL_COST = 25;     // 45
const uint TRADER_CHAIN_MYTHRIL_COST = 55;   // 70
const uint TRADER_CHAIN_ADAMANT_COST = 105;  // 125
const uint TRADER_WEAPON_MUSKET_COST = 55;   // 63
const uint TRADER_WEAPON_HANDCANNON_COST = 105; // 120
const uint TRADER_ARROW_IRON_COST = 12;
const uint TRADER_ARROW_STEEL_COST = 20;
const uint TRADER_ARROW_PIERCING_COST = 40;
const uint TRADER_AMMO_ROUNDSHOT_COST = 10;

// -- APOTHECARY
const uint TRADER_POTION_FEATHER_COST = 8;
const uint TRADER_POTION_SWIFTNESS_COST = 18;
const uint TRADER_POTION_INVISIBILITY_COST = 10;
const uint TRADER_POTION_WATERBREATHING_COST = 7;
const uint TRADER_POTION_ROCK_SKIN_COST = 10;
const uint TRADER_POTION_REGENERATION_COST = 15;
const uint TRADER_POTION_SAPPING_COST = 20;
const uint TRADER_POTION_MYSTERY_COST = 30;

// -- ENCHANTER
const uint TRADER_SCROLL_HARVEST_COST = 3;
const uint TRADER_SCROLL_BUFFALO_COST = 20;
const uint TRADER_SCROLL_EARTH_COST = 20;
const uint TRADER_SCROLL_MINER_COST = 30;
const uint TRADER_SCROLL_DROUGHT_COST = 40;
const uint TRADER_SCROLL_GUARDIAN_COST = 20;
const uint TRADER_SCROLL_LIGHT_COST = 5;
const uint TRADER_SCROLL_DESTRUCTION_COST = 100;
const uint TRADER_SCROLL_UNDEAD_COST = 40;
const uint TRADER_SCROLL_RETURNING_COST = 30;

const uint TRADER_AURA_SHADOW_COST = 20;
const uint TRADER_AURA_OTHER_COST = 30;
const uint TRADER_AURA_TELEPORTATION_COST = 75;

// -- FARMING SHOP
const uint TRADER_SEED_GRAIN_COST = 5;
const uint TRADER_SEED_BUSH_COST = 5;
const uint TRADER_SEED_CACTUS_COST = 10;
const uint TRADER_GRAIN_COST = 5;
const uint TRADER_SEED_TREE_BUSHY_COST = 30;
const uint TRADER_SEED_TREE_PINE_COST = 50;
const uint TRADER_SEED_TREE_REDWOOD_COST = 80;
const uint TRADER_LEAF_COST = 3;

// -- PET SHOP

// bunny, pig, shark, bison
